### ISSUE TITLE
テストの実行方法を教えてください。

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/fluent-plugin-hatohol#1]
ちなみにやってみたことは以下の通りです。
1. test/run-test.rbの実行
   
   fluent-plugin-hatohol $ test/run-test.rb 
   /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- fluent/test   (LoadError)
           from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
           from test/run-test.rb:30:in `<main>'
2. fluent/testの位置をRUBYLIBに追加した。
   
   fluent-plugin-hatohol $ RUBYLIB=/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib test/run-test.rb
   Loaded suite test
   Started
   # E
   
   Error: test_default(BuildMessageTest::content)
   : NoMethodError: undefined method `event_router' for nil:NilClass
   /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:76:in`configure'
   /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:193:in `configure'
   /home/kyamato/fluent-plugin-hatohol/lib/fluent/plugin/out_hatohol.rb:34:in`configure'
   /home/kyamato/fluent-plugin-hatohol/test/test_build_message.rb:31:in `create_plugin'
   /home/kyamato/fluent-plugin-hatohol/test/test_build_message.rb:36:in`call_build_message'
   /home/kyamato/fluent-plugin-hatohol/test/test_build_message.rb:66:in `build_content'
   /home/kyamato/fluent-plugin-hatohol/test/test_build_message.rb:75:in`test_default'
        72:
        73:     def test_default
        74:       assert_equal("Message",
     => 75:                    build_content({}, {"message" => "Message"}))
        76:     end
        77:
        78:     def test_multiple

**Comment by kz0817** [comment]
実行環境は、Ubuntu 14.04 LTSです（LXC内）。上記1.を実行するまえにrequireで足りないパッケージを示すエラーが出たので、それらについては、gem installをして、エラーを抑止しました。

**Comment by kou** [comment]
Fluentdのテスト周りのAPIが変わっていたのが原因でした。

最新のFluentdで動くための変更をpushしたのでmasterで試してみてください。

**Comment by kou** [comment]
`RUBYLIB`はなくても動きます。

なぜ動かないかというとテストの実行にはRuby 1.9を使っていて、gem installしたのはRuby 2.1だからだと思います。

`ruby -S gem install fluentd bunny test-unit`とすると`RUBYLIB`を指定しなくても動くようになると思います。

**Comment by kz0817** [comment]
うまく行きました。ありがとうございます。
